import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db/mongoose';
import { Blog } from '@/lib/db/models/Blog';
import { generateBlogImages } from '@/lib/blogImages';

export const maxDuration = 300;

export async function GET(req: Request) {
  const auth = req.headers.get('authorization');
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  // Find published blogs that don't have a featured image yet.
  // $in: [null, ''] also catches documents where the field exists but is empty.
  // limit(1) keeps total runtime to ~3 DALL-E calls ≈ 45–55 s, within Vercel Hobby's 60 s cap.
  const blogs = await Blog.find(
    {
      status: 'published',
      autoGenerated: true,
      $or: [{ featuredImage: { $exists: false } }, { featuredImage: { $in: [null, ''] } }],
    },
    { title: 1, slug: 1, content: 1, imagePrompts: 1 },
  ).limit(1).lean();

  if (blogs.length === 0) {
    return NextResponse.json({ success: true, message: 'No blogs need images' });
  }

  const results: string[] = [];

  for (const blog of blogs) {
    try {
      const { featuredImage, content } = await generateBlogImages(
        blog.imagePrompts || {},
        blog.title,
        blog.content,
        blog.slug,
      );
      await Blog.findByIdAndUpdate(blog._id, { featuredImage, content });
      results.push(`✓ ${blog.title}`);
    } catch (err: any) {
      results.push(`✗ ${blog.title}: ${err.message}`);
    }
  }

  return NextResponse.json({ success: true, processed: results });
}
