import { NextResponse } from 'next/server';
import dbConnect from '@/lib/db/mongoose';
import { Blog } from '@/lib/db/models/Blog';
import { generateBlogImages } from '@/lib/blogImages';

// All 3 images per blog (thumbnail + 2 inline) use DALL-E, run in parallel → ~20 s/blog.
// 1 blog per run to stay reliably within Vercel Hobby's function timeout.
// Images for newly approved blogs are now handled by after() in the approve route.
export const maxDuration = 60;

export async function GET(req: Request) {
  const auth = req.headers.get('authorization');
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  await dbConnect();

  // Find published auto-generated blogs that don't have a featured image yet.
  // $in: [null, ''] also catches documents where the field exists but is falsy.
  const blogs = await Blog.find(
    {
      status: 'published',
      autoGenerated: true,
      $or: [{ featuredImage: { $exists: false } }, { featuredImage: { $in: [null, ''] } }],
    },
    { title: 1, slug: 1, content: 1, imagePrompts: 1, category: 1 },
  ).limit(1).lean();

  if (blogs.length === 0) {
    return NextResponse.json({ success: true, message: 'No blogs need images' });
  }

  // Process blogs sequentially so the 3 parallel DALL-E calls per blog don't
  // collide with the next blog's calls. Each blog takes ~20 s → 2 blogs ≈ 40 s total.
  const results: string[] = [];
  for (const blog of blogs) {
    try {
      const { featuredImage, content } = await generateBlogImages(
        blog.imagePrompts || {},
        blog.title,
        blog.content,
        blog.slug,
        blog.category || 'NEET counselling',
      );
      await Blog.findByIdAndUpdate(blog._id, { featuredImage, content });
      results.push(`✓ ${blog.title}`);
    } catch (err: any) {
      results.push(`✗ ${blog.title}: ${err.message}`);
    }
  }

  return NextResponse.json({ success: true, processed: results });
}
